/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const prove: (a: number, b: number, c: number, d: number) => void;
export const verify: (a: number, b: number, c: number, d: number) => void;
export const get_polynomial_size: (a: number, b: number) => void;
export const init: () => void;
export const __wbg_benchconfig_free: (a: number, b: number) => void;
export const __wbg_get_benchconfig_n: (a: number) => number;
export const __wbg_set_benchconfig_n: (a: number, b: number) => void;
export const __wbg_get_benchconfig_k: (a: number) => number;
export const __wbg_set_benchconfig_k: (a: number, b: number) => void;
export const __wbg_get_benchconfig_q: (a: number) => number;
export const __wbg_set_benchconfig_q: (a: number, b: number) => void;
export const benchconfig_new: (a: number, b: number, c: number) => number;
export const __wbg_benchresult_free: (a: number, b: number) => void;
export const benchresult_time_ms: (a: number) => number;
export const benchresult_success: (a: number) => number;
export const benchresult_error: (a: number, b: number) => void;
export const bench_cpu_sumcheck: (a: number) => number;
export const bench_gpu_sumcheck: (a: number) => number;
export const check_webgpu_available: () => number;
export const wasm_bindgen__convert__closures_____invoke__h37d500315fc510f4: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__hafdb9ab3e38cf30c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h3bd99db2baf4b10c: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__hd7038e97be204e89: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h5b72a26126d41099: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
