//! Autogenerated weights for pallet_escrow_arbitration
//!
//! This file was generated by the `frame-benchmarking-cli` using the
//! `pallet` subcommand. The values are placeholder estimates.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn register_agent() -> Weight;
    fn deregister_agent() -> Weight;
    fn update_agent_key() -> Weight;
    fn register_arbitrator() -> Weight;
    fn deregister_arbitrator() -> Weight;
    fn register_trader() -> Weight;
    fn update_trader_key() -> Weight;
    fn create_escrow() -> Weight;
    fn confirm_share() -> Weight;
    fn attest_funding() -> Weight;
    fn mark_paid() -> Weight;
    fn confirm_payment() -> Weight;
    fn raise_dispute() -> Weight;
    fn vote_dispute() -> Weight;
    fn submit_chain_signature() -> Weight;
    fn cancel_escrow() -> Weight;
    fn send_message() -> Weight;
    fn shielded_create() -> Weight;
    fn shielded_update() -> Weight;
    fn shielded_consume() -> Weight;
    fn shielded_dispute() -> Weight;
    fn verify_vss_share() -> Weight;
    fn resolve_dispute_with_frost() -> Weight;
    fn submit_frost_signature() -> Weight;
    fn mark_frost_signing_failed() -> Weight;
}

/// Weights for pallet_escrow_arbitration using the substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn register_agent() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn deregister_agent() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn update_agent_key() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn register_arbitrator() -> Weight {
        Weight::from_parts(40_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn deregister_arbitrator() -> Weight {
        Weight::from_parts(40_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn register_trader() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn update_trader_key() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn create_escrow() -> Weight {
        Weight::from_parts(100_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn confirm_share() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn attest_funding() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn mark_paid() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn confirm_payment() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn raise_dispute() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn vote_dispute() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn submit_chain_signature() -> Weight {
        Weight::from_parts(100_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn cancel_escrow() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn send_message() -> Weight {
        Weight::from_parts(40_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn shielded_create() -> Weight {
        Weight::from_parts(80_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn shielded_update() -> Weight {
        Weight::from_parts(60_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn shielded_consume() -> Weight {
        Weight::from_parts(70_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn shielded_dispute() -> Weight {
        Weight::from_parts(100_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn verify_vss_share() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn resolve_dispute_with_frost() -> Weight {
        Weight::from_parts(100_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn submit_frost_signature() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn mark_frost_signing_failed() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

/// For backwards compatibility with tests.
impl WeightInfo for () {
    fn register_agent() -> Weight {
        Weight::from_parts(50_000_000, 0)
    }

    fn deregister_agent() -> Weight {
        Weight::from_parts(50_000_000, 0)
    }

    fn update_agent_key() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }

    fn register_arbitrator() -> Weight {
        Weight::from_parts(40_000_000, 0)
    }

    fn deregister_arbitrator() -> Weight {
        Weight::from_parts(40_000_000, 0)
    }

    fn register_trader() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }

    fn update_trader_key() -> Weight {
        Weight::from_parts(20_000_000, 0)
    }

    fn create_escrow() -> Weight {
        Weight::from_parts(100_000_000, 0)
    }

    fn confirm_share() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }

    fn attest_funding() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }

    fn mark_paid() -> Weight {
        Weight::from_parts(20_000_000, 0)
    }

    fn confirm_payment() -> Weight {
        Weight::from_parts(50_000_000, 0)
    }

    fn raise_dispute() -> Weight {
        Weight::from_parts(25_000_000, 0)
    }

    fn vote_dispute() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }

    fn submit_chain_signature() -> Weight {
        Weight::from_parts(100_000_000, 0)
    }

    fn cancel_escrow() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }

    fn send_message() -> Weight {
        Weight::from_parts(40_000_000, 0)
    }

    fn shielded_create() -> Weight {
        Weight::from_parts(80_000_000, 0)
    }

    fn shielded_update() -> Weight {
        Weight::from_parts(60_000_000, 0)
    }

    fn shielded_consume() -> Weight {
        Weight::from_parts(70_000_000, 0)
    }

    fn shielded_dispute() -> Weight {
        Weight::from_parts(100_000_000, 0)
    }

    fn verify_vss_share() -> Weight {
        Weight::from_parts(50_000_000, 0)
    }

    fn resolve_dispute_with_frost() -> Weight {
        Weight::from_parts(100_000_000, 0)
    }

    fn submit_frost_signature() -> Weight {
        Weight::from_parts(50_000_000, 0)
    }

    fn mark_frost_signing_failed() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }
}
