name: Security Assistant
on:
 issue_comment:
   types: [created]
 pull_request_review_comment:
   types: [created]
 issues:
   types: [opened, assigned]
 pull_request_review:
   types: [submitted]
 pull_request:
   types: [opened, synchronize]
jobs:
 claude-response:
   runs-on: ubuntu-latest
   permissions:
    id-token: write
    contents: read
    issues: write
    pull-requests: write
   steps:
     - uses: actions/checkout@v4
     - uses: anthropics/claude-code-action@beta
       with:
         anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
         trigger_phrase: "/claude"
         timeout_minutes: 30
         allowed_tools: "Bash(cargo check),Bash(cargo clippy),Bash(cargo test),Bash(npm run build),Bash(npm test),Bash(bun test),Bash(tsc),Bash(git log),Bash(git diff),Bash(git show),Bash(find),Bash(grep),Bash(ls),Bash(cat),Bash(head),Bash(tail),Bash(awk),Bash(jq),Bash(sed),Bash(wc),Bash(sort),Bash(uniq),Bash(cut),Bash(xargs)"
         custom_instructions: |
            You are an anarchist security researcher working on critical infrastructure.
            One bug means lost lives. Think and review like Daniel Micay. Zero tolerance for vulns.

            Issue: [what breaks]
            Line: [file:line]
            Attack: [how exploitable]
            Fix: [how to fix]
            Example: |
                ```rust
                fn example() {
                  // Example code
                }
                ```
